"""vbridge auto-start — upper-layer orchestrator.

Two-part design:
  - Upper layer (this file): state detection, duplicate prevention, scheduling
  - Lower layer: `virtuoso-bridge start` binary (handles actual bridge setup)
"""

from __future__ import annotations

import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

from vbridge._display import ensure_display

STATE_DIR = Path.home() / ".cache" / "virtuoso_bridge"
STATE_JSON = STATE_DIR / "state.json"


def _read_state() -> dict | None:
    """Read state.json written by virtuoso-bridge start."""
    if not STATE_JSON.is_file():
        return None
    import json
    try:
        return json.loads(STATE_JSON.read_text())
    except Exception:
        return None


def _get_setup_path() -> str | None:
    """Get setup_path from state."""
    state = _read_state()
    if state:
        p = state.get("setup_path")
        if p and Path(p).is_file():
            return p
    return None


def _get_port() -> int:
    """Get bridge port from state or env."""
    state = _read_state()
    if state and state.get("port"):
        return int(state["port"])
    return int(os.environ.get("VB_LOCAL_PORT",
               os.environ.get("VB_REMOTE_PORT", "65432")))


def is_daemon_responding(port: int | None = None) -> bool:
    """Check if RAMIC daemon responds on port."""
    if port is None:
        port = _get_port()
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=2) as s:
            s.sendall(b'1+1\n')
            s.settimeout(2)
            return len(s.recv(64)) > 0
    except Exception:
        return False


def _is_virtuoso_running() -> bool:
    """Check if a virtuoso -replay process is already running."""
    try:
        r = subprocess.run(["pgrep", "-f", "virtuoso.*-replay"],
                           capture_output=True, timeout=3)
        return r.returncode == 0
    except Exception:
        return False


def _find_vbridge_bin() -> str:
    """Locate the virtuoso-bridge binary (co-located with vbridge)."""
    if getattr(sys, "frozen", False):
        # Frozen: virtuoso-bridge is in the same directory as vbridge
        my_dir = Path(sys.executable).parent
        candidate = my_dir / "virtuoso-bridge"
        if candidate.is_file():
            return str(candidate)
    # Fallback: PATH lookup
    found = shutil.which("virtuoso-bridge")
    if found:
        return found
    raise FileNotFoundError("virtuoso-bridge binary not found")


def _ensure_setup_il() -> str | None:
    """If virtuoso_setup.il is missing, generate it from state info."""
    state = _read_state()
    if not state:
        return None
    setup_path = state.get("setup_path")
    if not setup_path:
        return None
    if Path(setup_path).is_file():
        return setup_path

    work_dir = Path(setup_path).parent
    work_dir.mkdir(parents=True, exist_ok=True)

    daemon_file = work_dir / "ramic_bridge_daemon_3.py"
    il_file = work_dir / "ramic_bridge.il"
    if not daemon_file.is_file() or not il_file.is_file():
        return None

    port = state.get("port", 65432)
    if getattr(sys, "frozen", False):
        vbridge_bin = str(Path(sys.executable).parent / "vbridge")
        python_cmd = vbridge_bin
        daemon_ref = "daemon"
    else:
        python_cmd = sys.executable
        daemon_ref = str(daemon_file)
    content = (
        "; Virtuoso CIW Setup Script - RAMIC Bridge\n"
        "; Auto-generated by vbridge auto-start\n"
        "\n"
        f'setShellEnvVar("RB_DAEMON_PATH" "{daemon_ref}")\n'
        f'setShellEnvVar("RB_PYTHON_PATH" "{python_cmd}")\n'
        f'setShellEnvVar("RB_PORT" "{port}")\n'
        "\n"
        f'load("{il_file}")\n'
    )
    Path(setup_path).write_text(content, encoding="utf-8")
    print(f"[auto-start] Generated {setup_path}")
    return setup_path


def _run_bridge_start() -> int:
    """Ensure .env is valid, then call `virtuoso-bridge start`."""
    try:
        bridge = _find_vbridge_bin()
    except FileNotFoundError as e:
        print(f"[auto-start] {e}")
        return 1

    env_path = Path.home() / ".virtuoso-bridge" / ".env"
    need_init = True
    if env_path.is_file():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if s.startswith("VB_REMOTE_HOST=") and s.split("=", 1)[1].strip():
                need_init = False
                break

    if need_init:
        print("[auto-start] VB_REMOTE_HOST is empty, re-initializing...")
        subprocess.run([bridge, "init", "localhost", "--force"], timeout=10)

    # If state says running but daemon is dead, stop first to clear stale state
    state = _read_state()
    if state and not is_daemon_responding():
        subprocess.run([bridge, "stop"], timeout=10,
                       capture_output=True)

    r = subprocess.run([bridge, "start"], timeout=30)
    return r.returncode


def _wait_for_daemon(port: int, timeout: float = 60) -> bool:
    """Poll until daemon responds."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if is_daemon_responding(port):
            return True
        time.sleep(1)
    return False


def _launch_virtuoso(setup_path: str) -> subprocess.Popen | None:
    """Launch virtuoso -replay in background, detached."""
    log_dir = Path.home() / ".cache" / "virtuoso_bridge"
    log_dir.mkdir(parents=True, exist_ok=True)
    try:
        vlog = open(log_dir / "virtuoso_autostart.log", "w")
        proc = subprocess.Popen(
            ["virtuoso", "-replay", setup_path],
            stdout=vlog, stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        return proc
    except Exception as e:
        print(f"[auto-start] Failed to launch Virtuoso: {e}")
        return None


def startup_sequence(timeout: float = 60) -> int:
    """One-click startup. No prior init required.

    Flow:
      1. Check state: if daemon responding, done (no duplicate)
      2. Check setup files: if missing, call `virtuoso-bridge start`
      3. If virtuoso on PATH + X11 available: launch GUI
      4. Wait for daemon
    """
    port = _get_port()

    # --- State check: prevent duplicate ---
    if is_daemon_responding(port):
        print(f"[auto-start] Daemon already responding on port {port}.")
        return 0

    # --- Ensure setup files exist (call lower layer) ---
    setup_path = _get_setup_path()
    if not setup_path:
        print("[auto-start] Setup files missing, running bridge start...")
        rc = _run_bridge_start()
        if rc != 0:
            print("[auto-start] bridge start failed")
            return 1
        setup_path = _get_setup_path()
        if not setup_path:
            setup_path = _ensure_setup_il()
    else:
        print(f"[auto-start] Setup: {setup_path}")

    # Re-read port after start (may have changed)
    port = _get_port()

    if not setup_path:
        print("[auto-start] Bridge started but setup file not generated")
        return 0

    # Check again after start
    if is_daemon_responding(port):
        print(f"[auto-start] Daemon responding on port {port}.")
        return 0

    # --- Patch for frozen binary ---
    if getattr(sys, "frozen", False):
        from vbridge._frozen_patches import patch_setup_for_frozen
        patch_setup_for_frozen(setup_path)

    # --- Try to launch Virtuoso ---
    vbin = shutil.which("virtuoso")
    if not vbin:
        print(f"[auto-start] 'virtuoso' not on PATH")
        print(f"  Load in CIW: load(\"{setup_path}\")")
        return 0

    if not ensure_display():
        print(f"[auto-start] No X11 display available")
        print(f"  Load in CIW: load(\"{setup_path}\")")
        return 0

    if _is_virtuoso_running():
        print("[auto-start] Virtuoso already running, waiting...")
        if _wait_for_daemon(port, timeout=timeout):
            print("[auto-start] Ready!")
            return 0
        print(f"[auto-start] Timeout. load(\"{setup_path}\")")
        return 1

    print("[auto-start] Launching Virtuoso...")
    proc = _launch_virtuoso(setup_path)
    if not proc:
        return 1
    print(f"[auto-start] PID {proc.pid}, waiting for daemon...")
    if _wait_for_daemon(port, timeout=timeout):
        print("[auto-start] Ready!")
        return 0
    print("[auto-start] Timeout waiting for daemon")
    return 1


def wait_bridge_ready(timeout: float = 30) -> bool:
    """Block until bridge daemon is ready (for exec/load commands)."""
    if is_daemon_responding():
        return True
    return _wait_for_daemon(_get_port(), timeout=timeout)
